"""Immutable production stamp for the owner-approved native IIIC profile.

The ONLY stamp any sitting receives by default is the qualified floor015
mixture profile. The research draw-latent profile below is unqualified
(research_only_not_promoted artifact) and is stampable exclusively through
an explicit, doubly-gated local escape: the CORTEX_NWAY_RESEARCH_UNQUALIFIED
environment variable must be exactly "1" AND the deployment must be
non-production (no RELEASE stamp — deploy_app.sh writes cortex_web/RELEASE
on every production box, dev/CI checkouts have none). Any other
configuration fails closed to the production profile, the same idiom as
compute_rollout.py.
"""
from __future__ import annotations

import os

from . import config

RESPONSE_MODEL = "iiic_conditional_f1_v1"
RESPONSE_ARTIFACT_ID = "iiic-f1-crossfit-ensemble9-rd-20260720-floor015"
RESPONSE_ARTIFACT_SHA256 = (
    "2e35c400739d74778c33c6a9b2f2b8590a9c6f96f3b83841fc3fc6091db8457c"
)
SELECTOR_VERSION = "categorical_fisher_totalvar_v1"
PARTICLE_PROFILE_VERSION = "production_1200p_ess050_30mh_rd"
ENGINE_ALGORITHM_VERSION = "nway_protocol_0.2.0-rd"

# Research draw-latent (construction B) — NOT qualified for serving. Constants
# regenerated by n-way-protocol/scripts/make_engine_profile_constants.py and
# mirrored in cortex_web/apps/web/engine/nway_profile.ts; the sha is the
# canonical compact sorted-key JSON of the draws array (artifact_floor.py).
RESEARCH_DRAW_LATENT_ARTIFACT_ID = "iiic-f1-engine-frame-atoms17-rd-20260730"
RESEARCH_DRAW_LATENT_ARTIFACT_SHA256 = (
    "b25bd1c5e680b77df394eeccab0961bd1f67c1593ff3d4a144d0b92eb8f90fb8"
)
RESEARCH_UNQUALIFIED_ENV = "CORTEX_NWAY_RESEARCH_UNQUALIFIED"

_UNSET = object()


def production_nway_profile(candidate_bank_sha256: str) -> dict:
    """Return the exact browser/server replay contract for a new sitting."""
    return {
        "engineProfileId": "precision_nway_f1_ensemble9_floor015_fisher_v1",
        "responseModel": RESPONSE_MODEL,
        "responseArtifactId": RESPONSE_ARTIFACT_ID,
        "responseArtifactSha256": RESPONSE_ARTIFACT_SHA256,
        "selectorVersion": SELECTOR_VERSION,
        "particleProfileVersion": PARTICLE_PROFILE_VERSION,
        "engineAlgorithmVersion": ENGINE_ALGORITHM_VERSION,
        "candidateBankSha256": candidate_bank_sha256,
    }


def research_draw_latent_nway_profile(candidate_bank_sha256: str) -> dict:
    """The unqualified draw-latent stamp — never a default; see module doc."""
    return {
        "engineProfileId": "precision_nway_f1_engine_frame_atoms17_draw_latent_rd_v1",
        "responseModel": RESPONSE_MODEL,
        "responseArtifactId": RESEARCH_DRAW_LATENT_ARTIFACT_ID,
        "responseArtifactSha256": RESEARCH_DRAW_LATENT_ARTIFACT_SHA256,
        "selectorVersion": SELECTOR_VERSION,
        "particleProfileVersion": PARTICLE_PROFILE_VERSION,
        "engineAlgorithmVersion": ENGINE_ALGORITHM_VERSION,
        "candidateBankSha256": candidate_bank_sha256,
        "responseAggregation": "draw_latent",
    }


def research_unqualified_escape_active(environ=None, release=_UNSET) -> bool:
    """True ONLY for the explicit local research escape (see module doc).

    ``release`` is the deployed-commit stamp (config.RELEASE); production
    boxes always carry one, so a present release refuses regardless of env.
    """
    environ = os.environ if environ is None else environ
    release = config.RELEASE if release is _UNSET else release
    if release is not None:
        return False
    return environ.get(RESEARCH_UNQUALIFIED_ENV) == "1"


def nway_profile_for_new_session(candidate_bank_sha256: str, *,
                                 environ=None, release=_UNSET) -> dict:
    """The stamp a NEW sitting receives. Fails closed to production."""
    if research_unqualified_escape_active(environ, release):
        return research_draw_latent_nway_profile(candidate_bank_sha256)
    return production_nway_profile(candidate_bank_sha256)


def allowed_nway_profiles(candidate_bank_sha256: str, *,
                          environ=None, release=_UNSET) -> list[dict]:
    """Stamps a stored sitting may resume under the current configuration.

    The production profile is always resumable; a research draw-latent
    sitting resumes only while the escape is still active, and is refused
    (fail closed, no replay under a different model) everywhere else.
    """
    allowed = [production_nway_profile(candidate_bank_sha256)]
    if research_unqualified_escape_active(environ, release):
        allowed.append(research_draw_latent_nway_profile(candidate_bank_sha256))
    return allowed
