"""Immutable production stamps for the owner-approved native IIIC profiles.

Which stamp a NEW precision sitting receives is decided by the fail-closed
response-model rollout (`response_model_rollout`): OFF (the default) stamps
the floor015 mixture profile; "email_allowlist"/"all" stamp the QUALIFIED
draw-latent profile per the promotion checklist's staged phases. Unknown
rollout values fail closed to the mixture — the previous behavior — exactly
as compute_rollout.py falls back to serial. Existing sittings always retain
their persisted stamp: both production stamps are permanently resumable, so
flipping the rollout (either direction) changes only new-session
assignment, never an in-progress sitting's response model.

Two retired stamps are deliberately NOT resumable and never stampable:

- `precision_nway_f1_ensemble9_fisher_v1` (unfloored, served
  2026-07-20..08-01) — the owner accepted restarting the in-progress
  sittings that carry it.
- `precision_nway_f1_engine_frame_atoms17_draw_latent_rd_v1` — the
  pre-qualification research escape (CORTEX_NWAY_RESEARCH_UNQUALIFIED),
  removed once the qualified draw-latent path landed; local testing now
  uses the real rollout (CORTEX_NWAY_RESPONSE_ROLLOUT=all).

Resume fails SOFT for an unlisted stamp — GET /api/session/active returns
{"active": null}, the SPA offers a fresh start, and the next new sitting
supersedes the stored one — so retired sittings end cleanly, never with an
opaque error.
"""
from __future__ import annotations

from .rollout import email_allowlisted

RESPONSE_MODEL = "iiic_conditional_f1_v1"
RESPONSE_ARTIFACT_ID = "iiic-f1-crossfit-ensemble9-rd-20260720-floor015"
RESPONSE_ARTIFACT_SHA256 = (
    "2e35c400739d74778c33c6a9b2f2b8590a9c6f96f3b83841fc3fc6091db8457c"
)
SELECTOR_VERSION = "categorical_fisher_totalvar_v1"
PARTICLE_PROFILE_VERSION = "production_1200p_ess050_30mh_rd"
ENGINE_ALGORITHM_VERSION = "nway_protocol_0.2.0-rd"

# QUALIFIED draw-latent (construction B, nesting34 grid): 33 population
# quantile atoms at the out-of-sample heterogeneity plus the lambda_d = 1
# binary-nesting atom. Qualified by the amended locked campaign
# (n-way-protocol/docs/LOCKED_CAMPAIGN_PREREG_DRAW_LATENT.md). Constants
# regenerated by n-way-protocol/scripts/make_engine_profile_constants.py and
# mirrored in cortex_web/apps/web/engine/nway_profile.ts; the sha is the
# canonical compact sorted-key JSON of the draws array (artifact_floor.py).
QUALIFIED_DRAW_LATENT_ARTIFACT_ID = "iiic-f1-engine-frame-nesting34-20260730"
QUALIFIED_DRAW_LATENT_ARTIFACT_SHA256 = (
    "54aa8c76a64419ef7b45f754ae54795d38e4cdbee4b1b1a1a2e91f6d9de42204"
)
NWAY_RESPONSE_ROLLOUT_ENV = "CORTEX_NWAY_RESPONSE_ROLLOUT"


def production_nway_profile(candidate_bank_sha256: str) -> dict:
    """Return the exact browser/server replay contract for a new sitting."""
    return {
        "engineProfileId": "precision_nway_f1_ensemble9_floor015_fisher_v1",
        "responseModel": RESPONSE_MODEL,
        "responseArtifactId": RESPONSE_ARTIFACT_ID,
        "responseArtifactSha256": RESPONSE_ARTIFACT_SHA256,
        "selectorVersion": SELECTOR_VERSION,
        "particleProfileVersion": PARTICLE_PROFILE_VERSION,
        "engineAlgorithmVersion": ENGINE_ALGORITHM_VERSION,
        "candidateBankSha256": candidate_bank_sha256,
    }


def qualified_draw_latent_nway_profile(candidate_bank_sha256: str) -> dict:
    """The qualified draw-latent stamp (nesting34, construction B)."""
    return {
        "engineProfileId": "precision_nway_f1_nesting34_draw_latent_v1",
        "responseModel": RESPONSE_MODEL,
        "responseArtifactId": QUALIFIED_DRAW_LATENT_ARTIFACT_ID,
        "responseArtifactSha256": QUALIFIED_DRAW_LATENT_ARTIFACT_SHA256,
        "selectorVersion": SELECTOR_VERSION,
        "particleProfileVersion": PARTICLE_PROFILE_VERSION,
        "engineAlgorithmVersion": ENGINE_ALGORITHM_VERSION,
        "candidateBankSha256": candidate_bank_sha256,
        "responseAggregation": "draw_latent",
    }


def response_model_rollout(db, cfg: dict, code: str) -> str:
    """Which response model a NEW sitting is stamped with. Fails closed.

    "all"             -> the qualified draw-latent profile
    "email_allowlist" -> qualified draw-latent only for normalized emails in
                         nway_response_emails; mixture for everyone else
    "off" / unknown   -> the floor015 mixture profile (previous behavior)
    """
    rollout = (cfg or {}).get("nway_response_rollout")
    if rollout == "all":
        return "qualified_draw_latent"
    if rollout != "email_allowlist":
        return "mixture"
    return ("qualified_draw_latent"
            if email_allowlisted(db, cfg, code, "nway_response_emails")
            else "mixture")


def nway_profile_for_new_session(candidate_bank_sha256: str, *,
                                 db=None, cfg=None, code=None) -> dict:
    """The stamp a NEW sitting receives. Fails closed to the mixture.

    Callers that cannot supply (db, cfg, code) — none in production — get
    the mixture, the fail-closed default.
    """
    if (cfg is not None and code is not None
            and response_model_rollout(db, cfg, code) == "qualified_draw_latent"):
        return qualified_draw_latent_nway_profile(candidate_bank_sha256)
    return production_nway_profile(candidate_bank_sha256)


def allowed_nway_profiles(candidate_bank_sha256: str) -> list[dict]:
    """Stamps a stored sitting may resume — always both PRODUCTION stamps.

    Resume is independent of the rollout state: per the promotion checklist,
    a rollback changes only new-session assignment and never an in-progress
    sitting's response model. The retired legacy unfloored stamp and the
    removed research escape stamp are deliberately absent (see module doc).
    """
    return [
        production_nway_profile(candidate_bank_sha256),
        qualified_draw_latent_nway_profile(candidate_bank_sha256),
    ]
