// Independent Python/TypeScript draw-latent parity.
//
// __testdata__/draw_latent_reference.json is generated by
// gen_draw_latent_reference.py from the NORMATIVE oracle
// (n-way-protocol/draw_latent_rd/engine.py, construction B) running the
// PRODUCTION atoms17 artifact on a fixed cloud, fixed atom assignment, and
// fixed observations. The production engine must reproduce every post-update
// weight, cumulative log likelihood, and the final atom posterior within the
// established n-way parity tolerance (5e-7 — the same discipline as
// nway_integration.test.ts and the isolated port's python_parity.test.ts).

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  makeResponseObservation, nwayResponseRuntimeFor,
} from "./nway_likelihood";
import { NWAY_DRAW_LATENT_ARTIFACT, expectedDrawLatentNWayProfile } from "./nway_profile";
import { updateObservation } from "./particles";
import type {
  ComputeEngineInputs, ComputeSegmentMeta, ParticleState, PriorPieces,
} from "./types";

const reference = JSON.parse(readFileSync(fileURLToPath(new URL(
  "./__testdata__/draw_latent_reference.json", import.meta.url,
)), "utf8"));
const TOLERANCE = 5e-7;

function expectClose(actual: ArrayLike<number>, expected: number[]): void {
  expect(actual.length).toBe(expected.length);
  for (let i = 0; i < expected.length; i++) {
    expect(Math.abs(actual[i] - expected[i])).toBeLessThanOrEqual(TOLERANCE);
  }
}

function fixtureState(): ParticleState {
  const K = reference.K as number;
  const identity = Array.from({ length: K }, (_unused, i) =>
    Array.from({ length: K }, (_x, j) => Number(i === j)));
  const pieces: PriorPieces = { K, sigmaInv: identity, logDet: 0, L: identity };
  const inputs = {
    nwayProfile: expectedDrawLatentNWayProfile("a".repeat(64)),
  } as ComputeEngineInputs;
  return {
    N: reference.t.length,
    K,
    t: Float64Array.from((reference.t as number[][]).flat()),
    l: Float64Array.from((reference.l as number[][]).flat()),
    w: Float64Array.from(reference.initialWeights as number[]),
    logPrior: new Float64Array(reference.t.length),
    logLik: new Float64Array(reference.t.length),
    history: [],
    prior: { tPieces: pieces, lPieces: pieces },
    responseRuntime: nwayResponseRuntimeFor(inputs),
    atomIndex: Int32Array.from(reference.atomAssignment as number[]),
  };
}

describe("draw-latent Python oracle parity (production atoms17)", () => {
  it("uses the exact deployed atom table the oracle ran", () => {
    // The fixture atoms come from the canonical artifact JSON; they must be
    // the same floats as the deployed browser constants, key for key.
    expect(reference.atoms).toHaveLength(NWAY_DRAW_LATENT_ARTIFACT.draws.length);
    (reference.atoms as [number, number, number][]).forEach(
      ([beta, distractorLapse, weight], index) => {
        const draw = NWAY_DRAW_LATENT_ARTIFACT.draws[index];
        expect(beta).toBe(draw.beta);
        expect(distractorLapse).toBe(draw.distractorLapse);
        expect(weight).toBe(draw.weight);
      },
    );
  });

  it("matches every oracle update on the fixed trajectory", () => {
    const state = fixtureState();
    for (const step of reference.steps) {
      const spec = step.observation as {
        askedK: number; segmentIndex: number; rawPick: number; kind: string;
      };
      const segment = reference.segments[spec.segmentIndex] as ComputeSegmentMeta;
      updateObservation(state, makeResponseObservation(
        spec.askedK, segment, spec.rawPick,
        spec.kind === "binary" ? "spike" : "iiic",
      ));
      expectClose(state.w, step.weights as number[]);
      expectClose(state.logLik, step.logLik as number[]);
    }
    // Final inferred draw distribution — posterior mass per artifact atom.
    const mass = new Array<number>(reference.atoms.length).fill(0);
    for (let n = 0; n < state.N; n++) mass[state.atomIndex![n]] += state.w[n];
    expectClose(mass, reference.atomPosterior as number[]);
  });
});
