// Independent Python/TypeScript draw-latent parity.
//
// __testdata__/draw_latent_reference.json is generated by
// gen_draw_latent_reference.py from the NORMATIVE oracle
// (n-way-protocol/draw_latent_rd/engine.py, construction B) running the
// PRODUCTION atoms17 artifact on a fixed cloud, fixed atom assignment, and
// fixed observations. The production engine must reproduce every post-update
// weight, cumulative log likelihood, and the final atom posterior within the
// established n-way parity tolerance (5e-7 — the same discipline as
// nway_integration.test.ts and the isolated port's python_parity.test.ts).

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";

import {
  makeResponseObservation, nwayResponseRuntimeFor,
} from "./nway_likelihood";
import {
  NWAY_DRAW_LATENT_ARTIFACT, NWAY_QUALIFIED_DRAW_LATENT_ARTIFACT,
  expectedDrawLatentNWayProfile, expectedQualifiedDrawLatentNWayProfile,
} from "./nway_profile";
import { updateObservation } from "./particles";
import type {
  ComputeEngineInputs, ComputeSegmentMeta, ParticleState, PriorPieces,
} from "./types";

const reference = JSON.parse(readFileSync(fileURLToPath(new URL(
  "./__testdata__/draw_latent_reference.json", import.meta.url,
)), "utf8"));
const referenceNesting34 = JSON.parse(readFileSync(fileURLToPath(new URL(
  "./__testdata__/draw_latent_reference_nesting34.json", import.meta.url,
)), "utf8"));
const TOLERANCE = 5e-7;

function expectClose(actual: ArrayLike<number>, expected: number[]): void {
  expect(actual.length).toBe(expected.length);
  for (let i = 0; i < expected.length; i++) {
    expect(Math.abs(actual[i] - expected[i])).toBeLessThanOrEqual(TOLERANCE);
  }
}

function fixtureState(
  fixture: typeof reference,
  profile: ReturnType<typeof expectedDrawLatentNWayProfile>,
): ParticleState {
  const K = fixture.K as number;
  const identity = Array.from({ length: K }, (_unused, i) =>
    Array.from({ length: K }, (_x, j) => Number(i === j)));
  const pieces: PriorPieces = { K, sigmaInv: identity, logDet: 0, L: identity };
  const inputs = { nwayProfile: profile } as ComputeEngineInputs;
  return {
    N: fixture.t.length,
    K,
    t: Float64Array.from((fixture.t as number[][]).flat()),
    l: Float64Array.from((fixture.l as number[][]).flat()),
    w: Float64Array.from(fixture.initialWeights as number[]),
    logPrior: new Float64Array(fixture.t.length),
    logLik: new Float64Array(fixture.t.length),
    history: [],
    prior: { tPieces: pieces, lPieces: pieces },
    responseRuntime: nwayResponseRuntimeFor(inputs),
    atomIndex: Int32Array.from(fixture.atomAssignment as number[]),
  };
}

function assertOracleTrajectory(
  fixture: typeof reference,
  profile: ReturnType<typeof expectedDrawLatentNWayProfile>,
): void {
  const state = fixtureState(fixture, profile);
  for (const step of fixture.steps) {
    const spec = step.observation as {
      askedK: number; segmentIndex: number; rawPick: number; kind: string;
    };
    const segment = fixture.segments[spec.segmentIndex] as ComputeSegmentMeta;
    updateObservation(state, makeResponseObservation(
      spec.askedK, segment, spec.rawPick,
      spec.kind === "binary" ? "spike" : "iiic",
    ));
    expectClose(state.w, step.weights as number[]);
    expectClose(state.logLik, step.logLik as number[]);
  }
  // Final inferred draw distribution — posterior mass per artifact atom.
  const mass = new Array<number>(fixture.atoms.length).fill(0);
  for (let n = 0; n < state.N; n++) mass[state.atomIndex![n]] += state.w[n];
  expectClose(mass, fixture.atomPosterior as number[]);
}

describe("draw-latent Python oracle parity (production atoms17)", () => {
  it("uses the exact deployed atom table the oracle ran", () => {
    // The fixture atoms come from the canonical artifact JSON; they must be
    // the same floats as the deployed browser constants, key for key.
    expect(reference.atoms).toHaveLength(NWAY_DRAW_LATENT_ARTIFACT.draws.length);
    (reference.atoms as [number, number, number][]).forEach(
      ([beta, distractorLapse, weight], index) => {
        const draw = NWAY_DRAW_LATENT_ARTIFACT.draws[index];
        expect(beta).toBe(draw.beta);
        expect(distractorLapse).toBe(draw.distractorLapse);
        expect(weight).toBe(draw.weight);
      },
    );
  });

  it("matches every oracle update on the fixed trajectory", () => {
    assertOracleTrajectory(
      reference, expectedDrawLatentNWayProfile("a".repeat(64)),
    );
  });
});

describe("draw-latent Python oracle parity (QUALIFIED nesting34)", () => {
  it("uses the exact qualified atom table the oracle ran", () => {
    expect(referenceNesting34.atoms)
      .toHaveLength(NWAY_QUALIFIED_DRAW_LATENT_ARTIFACT.draws.length);
    (referenceNesting34.atoms as [number, number, number][]).forEach(
      ([beta, distractorLapse, weight], index) => {
        const draw = NWAY_QUALIFIED_DRAW_LATENT_ARTIFACT.draws[index];
        expect(beta).toBe(draw.beta);
        expect(distractorLapse).toBe(draw.distractorLapse);
        expect(weight).toBe(draw.weight);
      },
    );
    // The fixture's atom assignment covers the lambda_d = 1 nesting atom so
    // its uniform-distractor arithmetic is pinned cross-language.
    const nesting = referenceNesting34.atoms.length - 1;
    expect(referenceNesting34.atomAssignment).toContain(nesting);
    expect(referenceNesting34.atoms[nesting][1]).toBe(1);
  });

  it("matches every oracle update on the fixed trajectory", () => {
    assertOracleTrajectory(
      referenceNesting34,
      expectedQualifiedDrawLatentNWayProfile("a".repeat(64)),
    );
  });
});
