// Restricted-randomization label schedule — TS port of trainer/label_schedule.py
// (PECR: docs/LABEL_SCHEDULE_PECR.md). Replaces the trainer's deterministic
// label-sequence devices (strict skill-side alternation, bias-mode balance
// forcing, the mirror same-difficulty→flipped-label echo) with a randomized
// capped soft-tilted walk + STATIC paired-bin serving.
//
// Parity: every schedule decision is a pure function of
// (scheduleSeed, streamId, counter) through a splitmix64 finalizer that is
// bit-identical to the python reference AND to the seeder already in
// engine/rng.ts — golden cross-language vectors in labelSchedule.test.ts
// (generated by __testdata__/gen_trainer_reference.py). BigInt throughout
// the integer path; the >> 11n / 2^53 double conversion matches rng.ts.

const MASK64 = 0xffffffffffffffffn;
const PHI = 0x9e3779b97f4a7c15n;          // splitmix64 increment (rng.ts)
const STREAM_SALT = 0xd1b54a32d192ed03n;  // decorrelates streamId from seed

// One splitmix64 output step (state x + PHI, then the finalizer) —
// bit-identical to python trainer/label_schedule.py::sm64 and to the
// stateful closure in engine/rng.ts.
export function sm64(x: bigint): bigint {
  x = (x + PHI) & MASK64;
  let z = x;
  z = ((z ^ (z >> 30n)) * 0xbf58476d1ce4e5b9n) & MASK64;
  z = ((z ^ (z >> 27n)) * 0x94d049bb133111ebn) & MASK64;
  return z ^ (z >> 31n);
}

// Counter-based uniform stream: draw n is a pure function of
// (seed, streamId, n) — resumable, order-robust, bit-parity with python.
export class ScheduleRng {
  private key: bigint;
  private n: bigint = 0n;

  constructor(seed: number | bigint, streamId = 0) {
    const s = BigInt(seed) & MASK64;
    this.key = sm64(s ^ ((BigInt(streamId) * STREAM_SALT) & MASK64));
  }

  uniform(): number {
    const u = sm64((this.key + this.n * PHI) & MASK64);
    this.n += 1n;
    return Number(u >> 11n) / 9007199254740992; // 2^53
  }
}

// Deterministic 64-bit seed from a session identifier (FNV-1a over UTF-8).
// PECR §6.4: the schedule seed MUST vary per session — a fixed seed replays
// the label sequence across sessions. Deriving it from the server-issued
// trainingId also makes every session's label sequence auditable: analytics
// can reconstruct the served schedule exactly from the session record.
export function seedFromString(id: string): bigint {
  let h = 0xcbf29ce484222325n;                 // FNV-1a 64 offset basis
  const bytes = new TextEncoder().encode(id);
  for (const b of bytes) {
    h ^= BigInt(b);
    h = (h * 0x100000001b3n) & MASK64;         // FNV-1a 64 prime
  }
  return h;
}

export interface ScheduleParams {
  cap: number;      // hard imbalance backstop (only deterministic states)
  d0: number;       // soft anti-imbalance tilt starts at |D| >= d0
  gammaD: number;   // tilt beyond d0 (applied flat)
  r0: number;       // soft anti-run taper starts at run length r0
  gammaR: number;   // taper strength per run step beyond r0-1
  qMin: number;     // continue-probability floor (no interior certainty)
}

// Shipped default = the gate-feasible knee of the exact frontier
// (PECR §2-3): G = 0.5485, worst-envelope band inflation 9.8%.
export function defaultScheduleParams(): ScheduleParams {
  return { cap: 8, d0: 3, gammaD: 0.04, r0: 3, gammaR: 0.04, qMin: 0.25 };
}

// The probe/corrective TYPE flip is not a label stream; it needs tight
// dual-control bounds instead (probe fraction → 1/2, cap-bounded runs).
export function flipParams(): ScheduleParams {
  return { cap: 2, d0: 1, gammaD: 0.15, r0: 2, gammaR: 0.15, qMin: 0.30 };
}

// P(next side = +1 | imbalance d, signed run r). Pure — mirrors python.
export function pSideUp(d: number, r: number, p: ScheduleParams): number {
  if (d <= -p.cap) return 1.0;
  if (d >= p.cap) return 0.0;
  let pr = 0.5;
  if (Math.abs(d) >= p.d0) pr -= (d > 0 ? 1.0 : -1.0) * p.gammaD;
  const j = Math.abs(r);
  if (j >= p.r0) {
    const t = p.gammaR * (j - p.r0 + 1);
    pr += r > 0 ? -t : t;
  }
  if (r > 0) pr = Math.max(pr, p.qMin);
  else if (r < 0) pr = Math.min(pr, 1.0 - p.qMin);
  return Math.min(Math.max(pr, 0.0), 1.0);
}

// The runtime walk. propose() draws the next side (one counter tick);
// commit(side) advances the state with the side actually SERVED — which
// may deviate from the proposal (pool-exhaustion fallback), so the walk
// always tracks the true served-label imbalance. One instance per task:
// the learner sees one label stream per task across all modes.
export class SideScheduler {
  d = 0;
  run = 0;          // signed: +j = last j sides were +1
  clamped = 0;      // cap-discarded commits (telemetry)

  constructor(public p: ScheduleParams, public rng: ScheduleRng) {}

  propose(): number {
    const pu = pSideUp(this.d, this.run, this.p);
    return this.rng.uniform() < pu ? 1 : -1;
  }

  commit(side: number): void {
    const s = side > 0 ? 1 : -1;
    let dNew = this.d + s;
    if (Math.abs(dNew) > this.p.cap) {
      this.clamped += 1;
      dNew = Math.max(Math.min(dNew, this.p.cap), -this.p.cap);
    }
    this.d = dNew;
    this.run = this.run * s > 0 ? this.run + s : s;
  }
}

export const BIN_WIDTH = 0.2; // |s| bin width for paired-bin serving (§5c)

// STATIC paired-bin serving (PECR §5c) — the mirror device. Bins the
// candidate pool by |s|; eligible bins have BOTH labels present; the bin
// is chosen SIDE-BLIND by magnitude-profile × precision-availability
// (a bin is only as discriminating as its less-precise side — the F20
// lesson at bin level; dropping it inflated sharp-margin FG 0.60→0.80).
// Served MAGNITUDES match across sides to within one bin width BY
// CONSTRUCTION (the |s| channel has no dynamic component); the s_sd
// (perceived-ambiguity) channel is a BANK-CONTENT limitation recorded as
// the PECR §6.1 owner item — not closeable by serving.
//
// `want` is accepted but deliberately UNUSED — that unusedness IS the
// side-blindness property; do not "optimize" it into the choice.
//
// Returns a boolean mask over the candidates (the chosen bin — label
// masking is the caller's job), or null when no paired bin exists
// (degenerate pool ⇒ caller falls back to the legacy unconstrained argmax).
export function pairedBinChoice(
  sMean: number[], yStar: number[], _want: number, targetMag: number,
  sSd: number[] | null = null, width = BIN_WIDTH, rhoMag = 0.5,
): boolean[] | null {
  const n = sMean.length;
  const bins = new Array<number>(n);
  const pos = new Set<number>();
  const neg = new Set<number>();
  for (let i = 0; i < n; i++) {
    bins[i] = Math.floor(Math.abs(sMean[i]) / width);
    (yStar[i] === 1 ? pos : neg).add(bins[i]);
  }
  const paired = [...pos].filter((b) => neg.has(b)).sort((a, b) => a - b);
  if (!paired.length) return null;
  const t = targetMag;
  let best = -1;
  let bestW = -1.0;
  for (const b of paired) {
    const mid = (b + 0.5) * width;
    let w = Math.exp(-((mid - t) ** 2) / (2 * (rhoMag * Math.max(t, 0.3)) ** 2));
    if (sSd !== null) {
      let minPos = Infinity;
      let minNeg = Infinity;
      for (let i = 0; i < n; i++) {
        if (bins[i] !== b) continue;
        if (yStar[i] === 1) minPos = Math.min(minPos, sSd[i]);
        else minNeg = Math.min(minNeg, sSd[i]);
      }
      const worst = Math.max(minPos, minNeg);
      w /= 1 + worst * worst;
    }
    if (w > bestW) {
      best = b;
      bestW = w;
    }
  }
  return bins.map((b) => b === best);
}
